//! Server side of `rill_stream_v1` (protocols/rill-stream-v1.xml): the
//! vector-native window content protocol — W4/D4 in specs/wgpu-renderer.md.
//! Types are generated by wayland-scanner; the request handling lives in
//! `main.rs` (`Dispatch` impls on `Rill`).
#![allow(missing_docs, clippy::all)]

// The generated modules reference these names via `super::`.
#[allow(clippy::single_component_path_imports)]
use wayland_server;

pub mod __interfaces {
    use wayland_server::backend as wayland_backend;
    use wayland_server::protocol::__interfaces::*;
    wayland_scanner::generate_interfaces!("../../protocols/rill-stream-v1.xml");
}
use self::__interfaces::*;
use wayland_server::protocol::*;

wayland_scanner::generate_server_code!("../../protocols/rill-stream-v1.xml");
