//! A notes application (plan § Application Phase 5): list, create, open, and
//! edit notes with no downloaded code. Pages are Rill documents generated by
//! runtime KDL compilation; the "Create" button submits an ACTION.
//!
//! ```bash
//! notes-app <content-root> --identity <server-id> --data <notes-dir> [--port N]
//! ```
//!
//! The content root still serves static files (so the app's manifest/pack
//! live there); this binary registers a dynamic `/notes` prefix on top.

use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use rill_auth::Identity;
use rill_protocol::{ActionValue, Status};
use rill_server::{AppHandler, Server, ServerConfig, verify_expected};

/// One note: a filename-safe id and its text.
struct Notes {
    dir: PathBuf,
    lock: Mutex<()>,
}

impl Notes {
    fn new(dir: PathBuf) -> Notes {
        std::fs::create_dir_all(&dir).expect("notes dir");
        Notes { dir, lock: Mutex::new(()) }
    }

    fn list(&self) -> Vec<(String, String)> {
        let _g = self.lock.lock().unwrap();
        let mut out = Vec::new();
        if let Ok(entries) = std::fs::read_dir(&self.dir) {
            for e in entries.flatten() {
                if let Some(id) = e.file_name().to_str().and_then(|n| n.strip_suffix(".txt")) {
                    let body = std::fs::read_to_string(e.path()).unwrap_or_default();
                    out.push((id.to_string(), body));
                }
            }
        }
        out.sort();
        out
    }

    fn get(&self, id: &str) -> Option<String> {
        if !valid_id(id) {
            return None;
        }
        let _g = self.lock.lock().unwrap();
        std::fs::read_to_string(self.dir.join(format!("{id}.txt"))).ok()
    }

    fn create(&self, title: &str) -> Result<String, Status> {
        let title = title.trim();
        if title.is_empty() || title.len() > 200 {
            return Err(Status::Internal);
        }
        let _g = self.lock.lock().unwrap();
        // Derive a filename-safe, unique id from the title.
        let base: String = title
            .chars()
            .map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_lowercase() } else { '-' })
            .collect();
        let base = base.trim_matches('-');
        let base = if base.is_empty() { "note" } else { base };
        let mut id = base.to_string();
        let mut n = 1;
        while self.dir.join(format!("{id}.txt")).exists() {
            n += 1;
            id = format!("{base}-{n}");
        }
        std::fs::write(self.dir.join(format!("{id}.txt")), title)
            .map_err(|_| Status::Internal)?;
        Ok(id)
    }

    /// Write a note, optionally only if it still reads as the caller last
    /// saw it.
    ///
    /// The check happens under the same lock as the write, which is the
    /// whole point: reading the current bytes, comparing, and writing must
    /// be one step, or two savers can both pass the comparison and the
    /// second still lose the first's work.
    fn save(&self, id: &str, body: &str, expected: Option<&[(String, ActionValue)]>)
        -> Result<(), Status>
    {
        // A submitted body arrives as one ACTION field, capped at the wire
        // limit — advertise the same bound the client enforces (was 100 KB,
        // which the 1 KiB field limit made unreachable).
        if !valid_id(id) || body.len() > rill_protocol::MAX_FIELD_STRING {
            return Err(Status::Internal);
        }
        let _g = self.lock.lock().unwrap();
        let path = self.dir.join(format!("{id}.txt"));
        if !path.exists() {
            return Err(Status::NotFound);
        }
        if let Some(fields) = expected {
            // The subject is this note's body — the bytes `/notes/note/{id}/data`
            // serves, which is what the caller hashed.
            let current = std::fs::read(&path).map_err(|_| Status::Internal)?;
            verify_expected(fields, &current)?;
        }
        std::fs::write(path, body).map_err(|_| Status::Internal)
    }
}

fn valid_id(id: &str) -> bool {
    !id.is_empty()
        && id.len() <= 64
        && id.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'-')
}

/// KDL-escape a user string for embedding in generated source: backslash,
/// quote, and control characters (raw newlines/tabs would otherwise break
/// the KDL parse).
use rill_doc::kdl_escape;

fn compile(kdl: &str) -> Result<Vec<u8>, Status> {
    rill_appkit::compile_page("notes-app", kdl)
}

fn index_page(notes: &Notes) -> Result<Vec<u8>, Status> {
    let mut kdl = String::from(
        "style \"title\" size=26 weight=\"bold\" color=\"#1a1a2e\"\n\
         style \"muted\" color=\"#70708a\"\n\
         style \"card\" background=\"#eef0f8\" corner=10\n\n\
         state \"new_title\" initial=\"\"\n\
         state \"show_form\" initial=#false\n\n\
         column gap=12 padding=24 {\n\
         \trow gap=12 { text \"Notes\" style=\"title\"; spacer; \
         button \"New note\" { toggle \"show_form\" } }\n",
    );
    kdl.push_str(
        "\twhen \"show_form\" {\n\
         \t\tcolumn gap=8 padding=14 style=\"card\" {\n\
         \t\t\ttext_input bind=\"new_title\" placeholder=\"Note title…\" { submit \"/notes/actions/create\" { field \"title\" from=\"new_title\" } }\n\
         \t\t\trow gap=8 {\n\
         \t\t\t\tbutton \"Create\" { submit \"/notes/actions/create\" { field \"title\" from=\"new_title\" } }\n\
         \t\t\t\tbutton \"Cancel\" { toggle \"show_form\" }\n\
         \t\t\t}\n\
         \t\t}\n\
         \t}\n",
    );
    let notes_list = notes.list();
    if notes_list.is_empty() {
        kdl.push_str("\ttext \"No notes yet. Create one above.\" style=\"muted\"\n");
    } else {
        for (id, body) in &notes_list {
            let title = body.lines().next().unwrap_or("(untitled)");
            let rest: String = body.lines().skip(1).collect::<Vec<_>>().join(" ");
            let preview: String = rest.chars().take(70).collect();
            kdl.push_str(&format!(
                "\trow gap=8 padding=12 style=\"card\" {{ \
                 link {} target=\"/notes/note/{}\"; spacer; text {} style=\"muted\" }}\n",
                kdl_escape(title),
                id,
                kdl_escape(&preview),
            ));
        }
    }
    kdl.push('}');
    compile(&kdl)
}

fn note_page(notes: &Notes, id: &str) -> Option<Vec<u8>> {
    let body = notes.get(id)?;
    let kdl = format!(
        "style \"title\" size=22 weight=\"bold\" color=\"#1a1a2e\"\n\
         style \"muted\" color=\"#70708a\"\n\
         style \"card\" background=\"#eef0f8\" corner=10\n\n\
         state \"body\" initial={body}\n\n\
         column gap=12 padding=24 {{\n\
         \trow gap=12 {{ link \"← Notes\" target=\"/notes/index\"; spacer; text {id_disp} style=\"muted\" }}\n\
         \ttext \"Edit note\" style=\"title\"\n\
         \tcolumn gap=8 padding=14 style=\"card\" {{\n\
         \t\ttext_input bind=\"body\" multiline=#true\n\
         \t\trow gap=8 {{\n\
         \t\t\tbutton \"Save\" {{ submit \"/notes/actions/save/{id}\" {{ field \"body\" from=\"body\" }} }}\n\
         \t\t\tbutton \"Import from file…\" {{ pick_file into=\"body\" }}\n\
         \t\t}}\n\
         \t}}\n\
         \ttext \"Editing is declarative: the text input binds to state, Save submits an ACTION.\" style=\"muted\"\n\
         }}",
        body = kdl_escape(&body),
        id_disp = kdl_escape(id),
        id = id,
    );
    compile(&kdl).ok()
}


/// The index as data: which notes exist, and what each one is called.
///
/// TOML, like the meter's sibling, and for the same reason — the tree
/// already parses it everywhere and `rill get` prints it legibly. Titles are
/// escaped as TOML basic strings; a note called `he said "hi"` must not
/// produce a file a parser rejects.
fn index_data(notes: &Notes) -> Vec<u8> {
    let mut out = String::from("# rill notes — the index (see /notes for the same, drawn)\n");
    for (id, body) in notes.list() {
        let title = body.lines().next().unwrap_or("(untitled)");
        out.push_str("\n[[note]]\n");
        out.push_str(&format!("id = {}\n", toml_string(&id)));
        out.push_str(&format!("title = {}\n", toml_string(title)));
        out.push_str(&format!("bytes = {}\n", body.len()));
    }
    out.into_bytes()
}

/// A TOML basic string: quote, backslash and control characters escaped.
fn toml_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

struct NotesApp {
    notes: Notes,
}

impl AppHandler for NotesApp {
    fn get(&self, path: &str, _identity: &Identity) -> Option<Vec<u8>> {
        match path {
            "/notes" | "/notes/index" => index_page(&self.notes).ok(),
            "/notes/data" => Some(index_data(&self.notes)),
            other => {
                // A note's body, as itself. Not a document, not wrapped in
                // anything: the note *is* the bytes, so this is the smallest
                // honest representation of it — and the thing whose hash a
                // caller can hold onto to say "the version I read".
                if let Some(id) = other.strip_prefix("/notes/note/").and_then(|r| r.strip_suffix("/data")) {
                    return self.notes.get(id).map(String::into_bytes);
                }
                other.strip_prefix("/notes/note/").and_then(|id| note_page(&self.notes, id))
            }
        }
    }

    fn action(
        &self,
        path: &str,
        fields: &[(String, ActionValue)],
        _identity: &Identity,
    ) -> Result<Vec<u8>, Status> {
        if path == "/notes/actions/create" {
            let title = rill_appkit::field(fields, "title").ok_or(Status::Internal)?;
            self.notes.create(title)?;
            // Respond with the refreshed index.
            index_page(&self.notes)
        } else if let Some(id) = path.strip_prefix("/notes/actions/save/") {
            let body = rill_appkit::field(fields, "body").ok_or(Status::Internal)?;
            // Conditional when the caller said which revision it read;
            // unconditional otherwise, which is what the in-page Save button
            // still sends.
            self.notes.save(id, body, Some(fields))?;
            note_page(&self.notes, id).ok_or(Status::Internal)
        } else {
            Err(Status::NotFound)
        }
    }
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let mut root: Option<String> = None;
    let mut identity: Option<String> = None;
    let mut data = "./notes-data".to_string();
    let mut bind = "127.0.0.1".to_string();
    let mut port: u16 = 7331;
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--identity" => {
                identity = args.get(i + 1).cloned();
                i += 2;
            }
            "--data" => {
                data = args[i + 1].clone();
                i += 2;
            }
            "--bind" => {
                bind = args[i + 1].clone();
                i += 2;
            }
            "--port" => {
                port = args[i + 1].parse().expect("port");
                i += 2;
            }
            other if root.is_none() => {
                root = Some(other.to_string());
                i += 1;
            }
            other => {
                eprintln!("notes-app: unexpected argument {other}");
                std::process::exit(1);
            }
        }
    }
    let (Some(root), Some(identity)) = (root, identity) else {
        eprintln!("usage: notes-app <content-root> --identity <dir> [--data DIR] [--port N]");
        std::process::exit(1);
    };

    let runtime = tokio::runtime::Builder::new_multi_thread().enable_all().build().unwrap();
    runtime.block_on(async move {
        let cfg = ServerConfig::new(root, identity);
        let mut server = Server::bind(&bind, port, cfg).await.expect("bind");
        server.dynamic("/notes", Arc::new(NotesApp { notes: Notes::new(data.into()) }));
        eprintln!("notes-app: serving /notes on {bind}:{port}");
        server.run().await.expect("run");
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU32, Ordering};

    static N: AtomicU32 = AtomicU32::new(0);

    fn app() -> NotesApp {
        let dir = std::env::temp_dir().join(format!(
            "notes-app-test-{}-{}",
            std::process::id(),
            N.fetch_add(1, Ordering::Relaxed)
        ));
        let _ = std::fs::remove_dir_all(&dir);
        NotesApp { notes: Notes::new(dir) }
    }

    fn text(app: &NotesApp, path: &str) -> String {
        String::from_utf8(app.get(path, &Identity::Anonymous).expect(path)).expect("utf-8")
    }

    /// The index as facts: what exists, not how it looks. Parses as TOML,
    /// carries no document magic, and says nothing about presentation.
    #[test]
    fn the_index_data_lists_what_exists() {
        let a = app();
        let table: toml::Table = text(&a, "/notes/data").parse().expect("TOML");
        assert!(table.get("note").is_none(), "an empty store lists nothing");

        a.notes.create("First note").expect("create");
        a.notes.create("Second note").expect("create");

        let bytes = a.get("/notes/data", &Identity::Anonymous).unwrap();
        assert_ne!(&bytes[..4], b"RDOC", "a fact is not a document");
        let table: toml::Table = String::from_utf8(bytes).unwrap().parse().expect("TOML");
        let notes = table["note"].as_array().expect("array");
        assert_eq!(notes.len(), 2);
        let titles: Vec<&str> =
            notes.iter().map(|n| n["title"].as_str().expect("title")).collect();
        assert!(titles.contains(&"First note") && titles.contains(&"Second note"), "{titles:?}");
        assert!(notes[0]["id"].as_str().is_some(), "each note is addressable by id");
    }

    /// A note's data sibling is the note — the exact bytes, nothing wrapped
    /// around them. This is what a caller hashes to say which version it read.
    #[test]
    fn a_notes_data_sibling_is_its_body() {
        let a = app();
        let id = a.notes.create("Shopping").expect("create");
        assert_eq!(text(&a, &format!("/notes/note/{id}/data")), "Shopping");

        a.notes.save(&id, "Shopping\nmilk\neggs", None).expect("save");
        assert_eq!(text(&a, &format!("/notes/note/{id}/data")), "Shopping\nmilk\neggs");

        // The page for the same note is a document, and a different thing.
        let page = a.get(&format!("/notes/note/{id}"), &Identity::Anonymous).expect("page");
        assert_eq!(&page[..4], b"RDOC", "the page is still a document");

        // A note that does not exist has no data either way.
        assert!(a.get("/notes/note/nope/data", &Identity::Anonymous).is_none());
        assert!(a.get("/notes/note/../etc/data", &Identity::Anonymous).is_none());
    }

    /// The whole editing loop at its size ceiling: the page carries an
    /// editor, a body exactly at MAX_FIELD_STRING saves and round-trips
    /// through the data sibling, and one byte more is refused without
    /// disturbing what was saved. This is the test whose absence let a
    /// 100 KiB server bound quietly disagree with the client's 1 KiB cap.
    #[test]
    fn the_editing_loop_round_trips_at_the_field_ceiling() {
        let a = app();
        let id = a.notes.create("Ceiling").expect("create");
        let page = a.get(&format!("/notes/note/{id}"), &Identity::Anonymous).expect("page");
        let doc = rill_doc::decode(&page).expect("the page decodes");
        assert!(
            doc.nodes.iter().any(|n| matches!(n, rill_doc::Node::TextInput { .. })),
            "the note page carries an editor"
        );

        let save = format!("/notes/actions/save/{id}");
        let data = format!("/notes/note/{id}/data");
        let at_cap = "x".repeat(rill_protocol::MAX_FIELD_STRING);
        a.action(&save, &[("body".into(), ActionValue::Str(at_cap.clone()))], &Identity::Anonymous)
            .expect("a body at the cap saves");
        assert_eq!(text(&a, &data), at_cap, "and round-trips exactly");

        let over = "x".repeat(rill_protocol::MAX_FIELD_STRING + 1);
        a.action(&save, &[("body".into(), ActionValue::Str(over))], &Identity::Anonymous)
            .expect_err("one byte over is refused");
        assert_eq!(text(&a, &data), at_cap, "and the refusal changed nothing");
    }

    /// A stale write is refused, and refusing it changes nothing. The
    /// revision is the hash of exactly the bytes `/notes/note/{id}/data`
    /// serves, so a caller that read the note has everything it needs.
    #[test]
    fn a_write_against_a_stale_revision_is_refused() {
        let a = app();
        let id = a.notes.create("Plan").expect("create");
        let data = format!("/notes/note/{id}/data");
        let seen = a.get(&data, &Identity::Anonymous).expect("data");
        let revision = rill_store::Hash::of(&seen);

        let expected = |hash: rill_store::Hash| {
            vec![(
                rill_protocol::FIELD_EXPECTED.to_string(),
                ActionValue::Str(hash.to_string()),
            )]
        };

        // Somebody else writes first.
        a.notes.save(&id, "Plan\ntheirs", None).expect("their save");

        // The conditional write, against what we read, is refused...
        assert_eq!(
            a.notes.save(&id, "Plan\nmine", Some(&expected(revision))),
            Err(Status::Conflict)
        );
        // ...and nothing changed.
        assert_eq!(text(&a, &data), "Plan\ntheirs");

        // Re-read, re-try: it applies.
        let now = rill_store::Hash::of(a.get(&data, &Identity::Anonymous).unwrap().as_slice());
        a.notes.save(&id, "Plan\nmine", Some(&expected(now))).expect("fresh revision applies");
        assert_eq!(text(&a, &data), "Plan\nmine");

        // An action with no revision is unconditional, as the in-page Save
        // button still is.
        a.notes.save(&id, "Plan\nunconditional", Some(&[])).expect("no condition, no refusal");
        assert_eq!(text(&a, &data), "Plan\nunconditional");
    }

    /// A title is user input, and the index is a parsed format. Quotes,
    /// backslashes and newlines in a title must not produce a file that a
    /// TOML parser rejects — the same escaping discipline the KDL side got.
    #[test]
    fn hostile_titles_survive_the_data_index() {
        let a = app();
        for title in [
            "he said \"hi\"",
            "back\\slash",
            "line\nbreak",
            "tab\there",
        ] {
            a.notes.create(title).expect("create");
        }
        let table: toml::Table = text(&a, "/notes/data").parse().expect("hostile titles parse");
        let notes = table["note"].as_array().expect("array");
        assert_eq!(notes.len(), 4);
        let titles: Vec<&str> = notes.iter().map(|n| n["title"].as_str().unwrap()).collect();
        assert!(titles.contains(&"he said \"hi\""), "{titles:?}");
        // A title with a newline is stored whole; only its first line is the
        // title, which is what the drawn index shows too.
        assert!(titles.contains(&"line"), "{titles:?}");
    }
}
